# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1667d073cb54ad94d99e47c2e7a649265c95395d4a6c991b973ab65fc67651473c49ca25b96af81cca0a48eb86705c0bfaa8220c8089f46ba5b44ec3ce0f34f9

test:
  secret_key_base: c66d2104915a2765fc058be467391e2a11469e37749a357fc40fe3107e23b1d0409b5e711712b83c1e068ce932f4ccf0c323a688d4f26715a11c9e755c08082c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
